apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "aws-secrets-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aws-secrets-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aws-secrets-manager.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aws-secrets-manager.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "aws-secrets-manager.fullname" . }}-azure
            - configMapRef:
                name: {{ include "aws-secrets-manager.fullname" . }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}