apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-secrets-manager.fullname" . }}-azure
  labels:
    {{- include "aws-secrets-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.azure }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}