# Default values for aws-secrets-manager
replicaCount: 1

image:
  repository: dinhdobathi/aws-secrets-manager
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: "aws-sm-service"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::457085052934:role/aws-sm-service"

service:
  type: ClusterIP
  port: 5001

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: secrets-manager.example.com
      paths:
        - path: /
          pathType: Prefix

env:
  FLASK_ENV: "development"
  FLASK_DEBUG: "1"

secrets:
  azure:
    AZURE_CLIENT_ID: ""
    AZURE_CLIENT_SECRET: ""
    AZURE_TENANT_ID: ""
    AZURE_REDIRECT_URI: "https://secrets-manager.example.com/auth/callback"
    AZURE_GROUP_SECRETS_READERS: ""
    AZURE_GROUP_SECRETS_WRITERS: ""
    FLASK_SECRET_KEY: ""

configMap:
  AWS_ACCOUNTS: |
    {
      "development": {
        "name": "Development Account",
        "role_arn": "arn:aws:iam::457085052934:role/aws-sm-service",
        "aws_region": "us-east-1",
        "description": "Development environment"
      },
      "production": {
        "name": "Production Account",
        "role_arn": "arn:aws:iam::457085052934:role/aws-sm-service",
        "aws_region": "ap-southeast-1",
        "description": "Production environment"
      }
    }

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
